[package]
name = "test-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getrandom = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
